language: ruby
rvm:
#  - 1.9.3
  - 2.0.0
env:
  global:
    secure: gU9M90UU+UgZNdX378oZ9ugzuRXQsO9fHZCRue0/pXmG7YTmP1l3DX0i4W9ZFffdqiXKBBpkNn6y5vPd4A7JLBUpRjtb2QQxki1dk5i1+8N9zhKhC3kuL5ohuOVnwORz5VJbj9V2ubkZGPPQohc2kfWTQyoMwylU3nIEqvlcsWU=
branches:
  only:
    - master
script: rake travis
