language: ruby
rvm:
#  - 1.9.3
  - 2.0.0
env:
  global:
    secure: NhZg2IlFr0MO3WbR7Gv9Q5NJhauDpHalvmCk8cO8wHS5uijfCy9QUOudrxgpsWO7VFKRMhrqUbFr7Ceaxq7Rq3+rcOVSwe9QVQbJRFbJ22q3nXhBgJWzutwIEQ/8ndJdJ9DLxa2KJ5nX8QxP2yNsQ8qJVh0Dz2NWkMYmrPBzcL4=
branches:
  only:
    - master
script: rake travis
